### ISSUE TITLE
Add content of xRemoteDesktopAdmin_Readme.txt to README.md and remove original file

### ISSUE THREAD

**Issue by vors** [PowerShell/xRemoteDesktopAdmin#1]
@joeyaiello can you take care of it?

**Comment by joeyaiello** [comment]
Not a whole bunch of significant differences (most of it had already been reworded throughout the README), but I went ahead and ported over the small stuff. 

Didn't do it as a pull request (whoops!), but I'll do it right next time.

**Comment by vors** [comment]
@joeyaiello please, don't edit `master` branch directly.

**Comment by joeyaiello** [comment]
I swore I did this in `dev`! 

Whoops, the deletion I did in `master`. My bad...did you already revert, or should I just reflect it in `dev`?
