### ISSUE TITLE
UserAuthentication should have a default value

### ISSUE THREAD

**Issue by johnf** [PowerShell/xRemoteDesktopAdmin#16]
I'm using this resource with puppet. In it's current form it gets executed every single puppet run.
This is due to ```UserAuthentication``` not being mandatory, but yet noth having a default value. This means that at https://github.com/PowerShell/xRemoteDesktopAdmin/blob/dev/DSCResources/xRemoteDesktopAdmin/xRemoteDesktopAdmin.psm1#L131 it is always non-compliant as ```$UserAuthentication``` will be ```null```.

**Comment by johlju** [comment]
This issue have been resolved. This module has been decprecated and the issue was resolved in the resource RemoteDesktopAdmin in the module [ComputerManagementDsc](https://github.com/PowerShell/ComputerManagementDsc).
